title: OPSIS Cookbook
description: Beta for OPSIS internal cookbook
theme: just-the-docs

url: https://alisonpeard.github.io/opsis-cookbook

aux_links:
  Template Repository: https://github.com/alisonpeard/opsis-cookbook
